version: 1.0.{build}
max_jobs: 2
image: Visual Studio 2015
cache: 
- ReactWindows\packages -> **\packages.config
- '%USERPROFILE%\.nuget\packages -> **\project.json'  
- ChakraCore\Build\VcBuild\bin -> ChakraCore\lib\Common\*.h 

clone_script:
- cmd: >-
    git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
    cd %APPVEYOR_BUILD_FOLDER%
    git checkout -qf %APPVEYOR_REPO_COMMIT%
    git submodule update --init --recursive

before_build:
- nuget restore ReactWindows\ReactNative.sln

build_script:
- cmd: >-

    set DEVENV="%VS140COMNTOOLS%\..\IDE\devenv"

    %DEVENV% /build "Debug|x86" ReactWindows\ReactNative.sln

    %DEVENV% /build "ReleaseBundle|x64" ReactWindows\ReactNative.sln

    %DEVENV% /build "Debug|ARM" ReactWindows\ReactNative.sln

test:
  assemblies:
  - ReactWindows\ReactNative.Net46.Tests\bin\x64\**\*.Tests.dll
