version: 1.0.{build}
max_jobs: 2
image: Visual Studio 2015
cache: 
- ReactWindows\packages -> ReactWindows\**\packages.config
- '%USERPROFILE%\.nuget\packages -> ReactWindows\**\project.json'  
- ChakraCore\Build\VcBuild -> ChakraCore\lib\Common\*.h 

clone_script:
- cmd: >-
    @echo off

    echo APPVEYOR_REPO_BRANCH -- %APPVEYOR_REPO_BRANCH%

    echo APPVEYOR_REPO_NAME -- %APPVEYOR_REPO_NAME%

    echo APPVEYOR_BUILD_FOLDER -- %APPVEYOR_BUILD_FOLDER%

    git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%

    cd %APPVEYOR_BUILD_FOLDER%

    if not defined APPVEYOR_PULL_REQUEST_NUMBER (

      git checkout -qf %APPVEYOR_REPO_COMMIT%
   
    ) else (
    
      git fetch -q origin +refs/pull/%APPVEYOR_PULL_REQUEST_NUMBER%/merge:

      git checkout -qf FETCH_HEAD

    )

    git submodule update --init --recursive

before_build:
- ps: >-
    Get-ChildItem .\ChakraCore\Build\VcBuild * -recurse | ForEach-Object{$_.LastWriteTime = get-date}

    nuget restore ReactWindows\ReactNative.sln

build_script:
- cmd: >-
    set DEVENV="%VS140COMNTOOLS%\..\IDE\devenv"

    %DEVENV% /build "Debug|x86" ReactWindows\ReactNative.sln

    %DEVENV% /build "ReleaseBundle|x64" ReactWindows\ReactNative.sln

    %DEVENV% /build "Debug|ARM" ReactWindows\ReactNative.sln

test:
  assemblies:
  - ReactWindows\ReactNative.Net46.Tests\bin\x64\**\*.Tests.dll
