#
parameters:
  name: ''
  BuildPlatform: x86 # ARM, x86, x64

jobs:
  - job: ${{ parameters.name }}
    displayName: E2E Test
    dependsOn: Setup
    condition: ne( dependencies.Setup.outputs['checkPayload.shouldSkipPRBuild'], 'True' )

    pool:
      vmImage: $(VmImage)

    timeoutInMinutes: 60 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them

    steps:
      - checkout: self
        clean: true
        fetchDepth: 1 # the depth of commits to ask Git to fetch
        submodules: false
            
      - template: prepare-env.yml

      - task: CmdLine@2
        displayName: Set LocalDumps
        inputs:
          script: $(Build.SourcesDirectory)\.ado\SetupLocalDumps.cmd
          workingDirectory: $(Build.SourcesDirectory)

      - task: NuGetCommand@2
        displayName: NuGet restore - ReactUWPTestApp
        inputs:
          command: restore
          noCache: true
          restoreSolution: packages/E2ETest/windows/ReactUWPTestApp.sln
          verbosityRestore: Detailed # Options: quiet, normal, detailed

      # See Issue 6393 for details
      - powershell: |
          Invoke-WebRequest https://github.com/microsoft/WinAppDriver/releases/download/v1.1/WindowsApplicationDriver.msi -OutFile $(Agent.TempDirectory)\WinAppDriver.msi
          Start-Process msiexec -ArgumentList "/quiet","/x","{087BBF93-D9E3-4D27-BDBE-9C702E0066FC}" -Verb runAs -Wait
          Start-Process msiexec -ArgumentList "/quiet","/i","$(Agent.TempDirectory)\WinAppDriver.msi" -Verb runAs -Wait
        displayName: Replace WinAppDriver 1.2.1 with WinAppDriver 1.1
         
      - task: CmdLine@2
        displayName: run-windows
        inputs:
          script: yarn windows --no-packager --arch ${{ parameters.BuildPlatform }} --release --logging --msbuildprops BaseIntDir=$(BaseIntDir)
          workingDirectory: packages/E2ETest

      - task: PublishBuildArtifacts@1
        condition:  succeededOrFailed()
        timeoutInMinutes: 10
        inputs:    
          pathtoPublish: packages/E2ETest/msbuild.binlog 
          artifactName: 'ReactUWPTestApp build log' 
          publishLocation: 'Container'

      - task: CopyFiles@2
        displayName: Copy ReactUWPTestApp artifacts
        inputs:
          sourceFolder: $(Build.SourcesDirectory)/packages/E2ETest/windows/ReactUWPTestApp
          targetFolder: $(Build.StagingDirectory)/ReactUWPTestApp
          contents: AppPackages\**
        condition: succeededOrFailed()

      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact:ReactUWPTestApp"
        inputs:
          artifactName: ReactUWPTestApp
          pathtoPublish: $(Build.StagingDirectory)/ReactUWPTestApp
        condition: succeededOrFailed()

      # Wait for app to launch. A workaround to avoid WinAppDriver error: Failed to locate opened application window with appId
      - task: PowerShell@2
        displayName: Wait for app to launch
        inputs:
          targetType: inline # filePath | inline
          script: |
            Start-Sleep -Seconds 30

      - task: PowerShell@2
        displayName: 'Check TestApp'
        inputs:
          targetType: 'inline'
          script: 'if ((Get-Process React*) -eq $Null) { echo "TestApp is not running"; exit 1}'

      - task: CmdLine@2
        displayName: mkdir errorShots
        inputs:
          script: mkdir $(Build.SourcesDirectory)\packages\E2ETest\errorShots

      - task: CmdLine@2
        displayName: run e2etest
        inputs:
          script: yarn run e2etest
          workingDirectory: packages/E2ETest

      - task: CopyFiles@2
        displayName: Copy tree dump output files
        inputs:
          sourceFolder: $(LocalAppData)\Packages\ReactUWPTestApp_kc2bncckyf4ap\LocalState
          targetFolder: $(Build.StagingDirectory)/ReactUWPTestAppTreeDump
          contents: TreeDump\**
        condition: succeededOrFailed()

      - task: CopyFiles@2
        displayName: Copy tree dump screenshots
        inputs:
          sourceFolder: $(Build.SourcesDirectory)\packages\E2ETest\errorShots
          targetFolder: $(Build.StagingDirectory)/ReactUWPTestAppTreeDump
        condition: succeededOrFailed()

      - task: PowerShell@2
        displayName: "MSInfo32"
        inputs:
          targetType: "inline"
          script: "Start-Process msinfo32 -ArgumentList '/report $(Build.StagingDirectory)\\ReactUWPTestAppTreeDump\\msinfo32.txt' -Wait"
        condition: failed()

      - task: PowerShell@2
        displayName: "Get-ShellScaling"
        inputs:
          targetType: "inline"
          script: ". $(Build.SourcesDirectory)\\.ado\\Get-ShellScaling.ps1 > $(Build.StagingDirectory)\\ReactUWPTestAppTreeDump\\scaleFactor.txt"
        condition: failed()

      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact:ReactUWPTestAppTreeDump"
        inputs:
          artifactName: ReactUWPTestAppTreeDump
          pathtoPublish: $(Build.StagingDirectory)/ReactUWPTestAppTreeDump
        condition: succeededOrFailed()

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: "JUnit"
          testResultsFiles: "packages/E2ETest/reports/*.log"
        condition: succeededOrFailed()

      - task: PowerShell@2
        displayName: "Show appium log"
        inputs:
          targetType: "inline"
          script: "Get-Content packages/E2ETest/reports/appium.txt | foreach {Write-Output $_}"
        condition: failed()

      - task: PowerShell@2
        displayName: List disksize at end of job
        inputs:
          targetType: inline # filePath | inline
          script: |
            Get-WmiObject Win32_LogicalDisk
        condition: succeededOrFailed()
