parameters:
  - name: buildEnvironment
    type: string
    default: PullRequest
    values: 
     - PullRequest 
     - Continuous
  - name: encodedKey
    type: string

jobs:
  - job: Set Up Certificate
    displayName: Set Up Certificate
    strategy:
      matrix:
        ${{if eq(parameters.buildEnvironment, 'Continuous')}}:
          ${{ if eq(parameters.encodedKey, 'sampleAppCPPEncodedKey') }}:
            EncodedKey: $(sampleAppCPPEncodedKey)
          ${{ if eq(parameters.encodedKey, 'reactUWPTestAppEncodedKey') }}:
            EncodedKey: $(reactUWPTestAppEncodedKey)
          ${{ if eq(parameters.encodedKey, 'playgroundEncodedKey') }}:
            EncodedKey: $(playgroundEncodedKey)
    steps:
      - task: PowerShell@2
        displayName: Generate PFX
        inputs:
          targetType: 'inline'
          script: |
            $PfxBytes = [System.Convert]::FromBase64String("$(EncodedKey)")
            $PfxPath = [System.IO.Path]::GetFullPath( (Join-Path -Path $(Build.SourcesDirectory) -ChildPath EncodedKey.pfx) )
            [System.IO.File]::WriteAllBytes("$PfxPath", $PfxBytes)
        condition: eq('${{ parameters.buildEnvironment }}', 'Continuous')