name: $(Date:yyyyMMdd).$(Rev:.r)

trigger: none # will disable CI builds entirely

pr: none

jobs:
  - job: RNWGithubPublish
    displayName: React-Native-Windows GitHub Publish
    pool:
      name: OE Standard Pool
      demands: ['VisualStudio_15.0', 'OnPrem -equals False']
    timeoutInMinutes: 120 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them
    steps:
      - checkout: self # self represents the repo where the initial Pipelines YAML file was found
        clean: true # whether to fetch clean each time
        fetchDepth: 2 # the depth of commits to ask Git to fetch
        lfs: false # whether to download Git-LFS files
        submodules: recursive # set to 'true' for a single level of submodules or 'recursive' to get submodules of submodules
        persistCredentials: true # set to 'true' to leave the OAuth token in the Git config after the initial fetch

      - task: CmdLine@1
        displayName: 'npm auth'
        inputs:
          filename: npm
          arguments: 'config set $(publishnpmfeed)/registry/:_authToken $(npmTokenOffice)'

      - task: CmdLine@2
        displayName: npm install
        inputs:
          script: npm install
          workingDirectory: RNWCPP

      - task: CmdLine@2
        displayName: npm run build
        inputs:
          script: npm run build
          workingDirectory: RNWCPP

      - task: CmdLine@2
        displayName: Do Publish
        inputs:
          script: node .ado/publish.js

      - task: CmdLine@1
        displayName: 'npm unauth'
        inputs:
          filename: npm
          arguments: 'config set $(publishnpmfeed)/registry/:_authToken XXXXX'

