# This file defines the Windows Visual Studio PR build steps used during the CI loop
name: $(Date:yyyyMMdd).$(Rev:.r)

trigger: none # will disable CI builds entirely

pr:
  - master

jobs:
  - template: templates/e2e-test-job.yml  # Template reference
    parameters:
      name: E2ETest
      pool:
        vmImage: vs2017-win2016
      BuildPlatform: x64
      UseRNFork: true
