# This file defines the Windows Visual Studio PR build steps used during the CI loop
name: $(Date:yyyyMMdd).$(Rev:r)

trigger: none # will disable CI builds entirely

pr:
  - master
  - "*-stable"

variables:
  - template: variables/msbuild.yml
  - template: variables/vs2019.yml

jobs:
  - job: RNW_WinUI3
    displayName: WinUI3 Playground
    dependsOn: Setup
    condition: ne( dependencies.Setup.outputs['checkPayload.shouldSkipPRBuild'], 'True' )
    strategy:
      matrix: # Why we only build some flavors: https://github.com/microsoft/react-native-windows/issues/4308
        X86:
          BuildConfiguration: Debug
          BuildPlatform: x86
    pool:
      name: 'winuibuildagents'
    timeoutInMinutes: 60
    cancelTimeoutInMinutes: 5

    steps:
      - checkout: self
        clean: false
        submodules: false

      - template: templates/prepare-env.yml

      - task: NuGetCommand@2
        displayName: NuGet restore - Playground
        inputs:
          command: restore
          restoreSolution: packages/playground/windows/Playground.sln
          verbosityRestore: Detailed # Options: quiet, normal, detailed
        
      - task: VSBuild@1
        displayName: VSBuild - Playground
        inputs:
          solution: packages/playground/windows/Playground.sln
          vsVersion: $(MSBuildVersion) # Optional. Options: latest, 16.0, 15.0, 14.0, 12.0, 4.0
          msbuildArchitecture: $(MSBuildArchitecture) # Optional. Options: x86, x64
          platform: $(BuildPlatform) # Optional
          configuration: $(BuildConfiguration) # Optional
          clean: true # Optional
          maximumCpuCount: false # Optional
          restoreNugetPackages: false # Optional
          msbuildArgs:
            /p:PreferredToolArchitecture=$(MSBuildPreferredToolArchitecture)
            /p:PlatformToolset=$(MSBuildPlatformToolset)
            /p:BaseIntDir=$(BaseIntDir)
            /p:AppxPackageSigningEnabled=false
            /p:UseWinUI3=true

      - task: PublishBuildArtifacts@1
        displayName: Upload crash dumps
        inputs:
          pathtoPublish: '$(Build.StagingDirectory)/CrashDumps/'
          artifactName: 'Crash dumps - $(Agent.JobName)-$(System.JobAttempt)'
        condition: failed()

