name: $(Date:yyyyMMdd).$(Rev:r)

trigger: none # will disable CI builds entirely

pr:
  - master
  - "*-stable"

variables:
  - template: variables/msbuild.yml
  - group: platform-override-zero-permission-token

jobs:
  - job: Setup
    variables:
      - template: variables/vs2019.yml
    steps:
      - task: powershell@2
        name: checkPayload
        displayName: "Check if build is required for this PR"
        inputs:
          targetType: filePath
          filePath: .ado/shouldSkipPRBuild.ps1

  - template: jobs/jschecks.yml

  - template: jobs/universal.yml
    parameters:
      buildEnvironment: PullRequest

  - template: jobs/desktop.yml
    parameters:
      buildEnvironment: PullRequest

  - template: jobs/nuget-desktop.yml

  - template: jobs/cli-init.yml
    parameters:
      buildEnvironment: PullRequest

  - template: jobs/playground.yml
    parameters:
      buildEnvironment: PullRequest

  - template: jobs/sample-apps.yml
    parameters:
      buildEnvironment: PullRequest

  - template: jobs/e2e-test.yml
    parameters:
      buildEnvironment: PullRequest

  - template: jobs/integration-test.yml
    parameters:
      buildEnvironment: PullRequest

  - template: jobs/macos-tests.yml
