# This file defines the Windows Visual Studio PR build steps used during the CI loop
name: $(Date:yyyyMMdd).$(Rev:r)

trigger: none # will disable CI builds entirely

pr:
  - master
  - "*-stable"

variables:
  - template: variables/msbuild.yml
  - template: variables/vs2019.yml

jobs:
  - job: CliInit
    displayName: Verify react-native init
    strategy:
      matrix: # Why we only build some flavors: https://github.com/microsoft/react-native-windows/issues/4308
        WinUI3_X86DebugCpp:
          language: cpp
          configuration: Debug
          platform: x86
          additionalInitArguments: --useWinUI3 true
          additionalRunArguments:
        WinUI3_X86DebugCs:
          language: cs
          configuration: Debug
          platform: x86
          additionalInitArguments: --useWinUI3 true
          additionalRunArguments:

    timeoutInMinutes: 40 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them
    pool:
      name: 'winuibuildagents'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.18.3' 
          checkLatest: false # Optional

      - template: templates/prepare-env.yml

      - template: templates/react-native-init.yml
        parameters:
          language: $(language)
          configuration: $(configuration)
          platform: $(platform)
          additionalInitArguments: $(additionalInitArguments)
          additionalRunArguments: $(additionalRunArguments)
