name: Publish
on:
  # File paths to consider in the event. Optional; defaults to all
  push:
    branches: # Array of patterns that match refs/heads
      - master

jobs:
  RnwNpmPublish:
    name: React-Native-Windows Npm Build Rev Publish
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v1

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "%GITHUB_CONTEXT%"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "%STRATEGY_CONTEXT%"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "%MATRIX_CONTEXT%"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "%JOB_CONTEXT%"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "%RUNNER_CONTEXT%"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "%STEPS_CONTEXT%"

      - name: yarn install
        run: yarn install --frozen-lockfile

      - run: yarn Build
